# Generated by Django 4.0.4 on 2022-06-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipes_info',
            fields=[
                ('RecipeId', models.IntegerField(primary_key=True, serialize=False)),
                ('AuthorId', models.IntegerField()),
                ('RecipeServings', models.FloatField(null=True)),
                ('Name', models.TextField(null=True)),
                ('AuthorName', models.TextField(null=True)),
                ('TotalTime', models.TextField(null=True)),
                ('DatePublished', models.TextField(null=True)),
                ('RecipeCategory', models.TextField(null=True)),
            ],
        ),
    ]
