# Generated by Django 4.0.4 on 2022-06-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_username_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthday_dayofyear_internal',
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(),
        ),
    ]
