# Generated by Django 4.0.4 on 2022-06-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_recipes_info_recipeingredientparts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes_info',
            name='RecipeIngredientQuantities',
            field=models.TextField(null=True),
        ),
    ]
