# Generated by Django 4.0.4 on 2022-06-24 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_profile_id_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cookbook',
        ),
        migrations.AddField(
            model_name='profile',
            name='cookbook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cook_book', to='accounts.recipes_info'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fav', to='accounts.recipes_info'),
        ),
    ]
