# Generated by Django 4.0.4 on 2022-06-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_profile_cookbook_profile_cookbook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cookbook',
        ),
        migrations.AddField(
            model_name='profile',
            name='cookbook',
            field=models.ManyToManyField(related_name='cook_book', to='accounts.recipes_info'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite',
            field=models.ManyToManyField(related_name='fav', to='accounts.recipes_info'),
        ),
    ]
