# Generated by Django 4.0.4 on 2022-06-24 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_remove_profile_cookbook_profile_cookbook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='interactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True)),
                ('review', models.TextField(null=True)),
                ('RecipeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.recipes_info')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'RecipeId')},
            },
        ),
    ]
