# Generated by Django 4.0.4 on 2022-06-24 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_interactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactions',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interactions',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - OK'), (3, '3 - Like'), (4, '4 - Really Like'), (5, '5 - Awesome')], null=True),
        ),
    ]
