# Generated by Django 4.0.4 on 2022-06-24 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_interactions_date_alter_interactions_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interactions',
            unique_together=set(),
        ),
    ]
